name: rapids-env
channels:
  - pytorch
  - nvidia
  - rapidsai
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - cuda-version=12.1
  - pytorch=2.6.0=py3.10_cuda12.1*
  - pytorch-cuda=12.1
  - cudf=24.06
  - cuml=24.06
  - cugraph=24.06
  - dask-cuda=24.06
  - torchvision
  - torchaudio
  - pip
  - pip:
      - accelerate==1.6.0
      - transformers==4.51.1
      - vllm==0.8.3
      - datasets==3.5.0
      - peft==0.15.1
      - flash_attn==2.7.4.post1
      - xformers==0.0.29.post2
      - fastapi==0.115.12
      - uvicorn==0.34.0
      - wandb==0.19.9
      - ray==2.43.0
      - openai==1.72.0